//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class IdMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/Id";
        public override string RosMessageName => k_RosMessageName;

        public string identifier;

        public IdMsg()
        {
            this.identifier = "";
        }

        public IdMsg(string identifier)
        {
            this.identifier = identifier;
        }

        public static IdMsg Deserialize(MessageDeserializer deserializer) => new IdMsg(deserializer);

        private IdMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.identifier);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.identifier);
        }

        public override string ToString()
        {
            return "IdMsg: " +
            "\nidentifier: " + identifier.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
