//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class IdServiceRequest : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/IdService";
        public override string RosMessageName => k_RosMessageName;

        public IdMsg input;

        public IdServiceRequest()
        {
            this.input = new IdMsg();
        }

        public IdServiceRequest(IdMsg input)
        {
            this.input = input;
        }

        public static IdServiceRequest Deserialize(MessageDeserializer deserializer) => new IdServiceRequest(deserializer);

        private IdServiceRequest(MessageDeserializer deserializer)
        {
            this.input = IdMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.input);
        }

        public override string ToString()
        {
            return "IdServiceRequest: " +
            "\ninput: " + input.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
