//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class IdServiceResponse : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/IdService";
        public override string RosMessageName => k_RosMessageName;

        public IdMsg output;

        public IdServiceResponse()
        {
            this.output = new IdMsg();
        }

        public IdServiceResponse(IdMsg output)
        {
            this.output = output;
        }

        public static IdServiceResponse Deserialize(MessageDeserializer deserializer) => new IdServiceResponse(deserializer);

        private IdServiceResponse(MessageDeserializer deserializer)
        {
            this.output = IdMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.output);
        }

        public override string ToString()
        {
            return "IdServiceResponse: " +
            "\noutput: " + output.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
